server {
    listen ${PORT};
    server_name _;

    location ~* "^/[0-9a-f]{8}$" {
        proxy_pass ${BACKEND_URL}/r$request_uri;
        proxy_set_header Host $proxy_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_ssl_server_name on;
        proxy_set_header X-Api-Key ${API_KEY};
    }

    location /api {
        proxy_pass ${BACKEND_URL};
        proxy_set_header Host $proxy_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_ssl_server_name on;
        proxy_set_header X-Api-Key ${API_KEY};
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}