// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ShortLink struct {
	ID          pgtype.UUID        `json:"id"`
	OriginalUrl string             `json:"original_url"`
	ShortCode   string             `json:"short_code"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
