// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package postgres

import (
	"context"
)

const getByShortCode = `-- name: GetByShortCode :one
SELECT id, original_url, short_code, created_at
FROM short_links
WHERE short_code = $1
`

func (q *Queries) GetByShortCode(ctx context.Context, shortCode string) (ShortLink, error) {
	row := q.db.QueryRow(ctx, getByShortCode, shortCode)
	var i ShortLink
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortCode,
		&i.CreatedAt,
	)
	return i, err
}
